In [ ]:
import cv2 as cv
import numpy as np
max_h = 0
max_w = 0
for i in range(1,1681):
    name = './current_data/AllImages/1' + str(i).zfill(8) + '.bmp'
    img = cv.imread(name)
    if img is None:
        pass
    else:
        img_h, img_w, ch = img.shape
        print(name)
        if img_h > max_h:
            max_h = img_h
        if img_w > max_w:
            max_w = img_w
print('max_h: %d, max_w: %d' % (max_h, max_w))

In [1]:
import cv2 as cv
import numpy as np
import os
new_h = 844
new_w = 1238
for i in range(1,1681):
    path = './current_data/AllImages/1' + str(i).zfill(8) + '.bmp'
    root, name = os.path.split(path)
    img = cv.imread(path)
    if img is None:
        pass
    else:
        img_h, img_w, ch = img.shape
        padding = np.full((new_h,new_w,3),(34,47,32), dtype=np.uint8)
        padding[0:img_h, 0:img_w] = img
        cv.imwrite('./pad/'+ name, padding)


In [45]:
import torch
a = torch.arange(60)
a = torch.reshape(a,(3,2,10))
b = torch.stack([a,a,a,a])
print(b.shape)

torch.Size([4, 3, 2, 10])


In [46]:
print(a)

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]])


In [49]:
m = torch.randint(1,100,size=(2,5))
print(m)
c = [torch.mul(a[i], torch.index_select(m,1,torch.tensor(i))) for i in range(3)]

tensor([[96, 24, 97,  8, 85],
        [ 6, 81, 76, 34, 22]])


In [11]:
import torch
a = torch.arange(10).reshape(2,5)
c = torch.rand(2)
print(a)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [15]:
b = []
for i in range(5):
    b.append(torch.rand(2))
print(b)

[tensor([0.1750, 0.4232]), tensor([0.7378, 0.1074]), tensor([0.1369, 0.4922]), tensor([0.8224, 0.6093]), tensor([0.9875, 0.0024])]


In [18]:
d = torch.stack(b).transpose(1,0)
print(d)
print(d.shape)

tensor([[0.1750, 0.7378, 0.1369, 0.8224, 0.9875],
        [0.4232, 0.1074, 0.4922, 0.6093, 0.0024]])
torch.Size([2, 5])


In [19]:
d = torch.stack(b, dim=1)
print(d)
print(d.shape)

tensor([[0.1750, 0.7378, 0.1369, 0.8224, 0.9875],
        [0.4232, 0.1074, 0.4922, 0.6093, 0.0024]])
torch.Size([2, 5])


In [26]:
a = torch.arange(6).reshape((2,3))

b = torch.arange(6).reshape((2,3))
print(a, b)

tensor([[0, 1, 2],
        [3, 4, 5]]) tensor([[0, 1, 2],
        [3, 4, 5]])


In [27]:
a*b

tensor([[ 0,  1,  4],
        [ 9, 16, 25]])