In [2]:
import os
from dataloader import HRSC2016
from tqdm import tqdm
from torch.utils.data import DataLoader
from torch.utils.data.dataset import Dataset
from collater import *
from model import *
ds = HRSC2016()
collater = Collater(scales=800)
loader = DataLoader(
    dataset=ds,
    batch_size=4,
    num_workers=8,
    collate_fn=collater,
    shuffle=False)
pbar = tqdm(enumerate(loader), total=len(loader))
model = RecurrentAttention(4, 128,128,3,3,256)
for i, (ni,batch) in enumerate(pbar):
    imgs, gt_boxes = batch['image'], batch['boxes']
    b,c,h,w = imgs.shape
    g_t = model(imgs)
    print(g_t.shape)
    





  0%|                                                   | 0/157 [00:00<?, ?it/s]


KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/chs/anaconda3/envs/cmap/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/chs/anaconda3/envs/cmap/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/chs/py/cmap/collater.py", line 28, in __call__
    bboxes = [sample['boxes'] for sample in batch]
  File "/home/chs/py/cmap/collater.py", line 28, in <listcomp>
    bboxes = [sample['boxes'] for sample in batch]
KeyError: 'boxes'


In [ ]:
import cv2 as cv
import numpy as np
max_h = 0
max_w = 0
for i in range(1,1681):
    name = './current_data/AllImages/1' + str(i).zfill(8) + '.bmp'
    img = cv.imread(name)
    if img is None:
        pass
    else:
        img_h, img_w, ch = img.shape
        print(name)
        if img_h > max_h:
            max_h = img_h
        if img_w > max_w:
            max_w = img_w
print('max_h: %d, max_w: %d' % (max_h, max_w))

In [1]:
import cv2 as cv
import numpy as np
import os
new_h = 844
new_w = 1238
for i in range(1,1681):
    path = './current_data/AllImages/1' + str(i).zfill(8) + '.bmp'
    root, name = os.path.split(path)
    img = cv.imread(path)
    if img is None:
        pass
    else:
        img_h, img_w, ch = img.shape
        padding = np.full((new_h,new_w,3),(34,47,32), dtype=np.uint8)
        padding[0:img_h, 0:img_w] = img
        cv.imwrite('./pad/'+ name, padding)


SyntaxError: invalid syntax (<ipython-input-2-22d6d8d38387>, line 1)

In [2]:
a = long(1)

NameError: name 'long' is not defined

In [3]:
a = torch.tensor([1,1])

In [4]:
a.shape

torch.Size([2])

In [11]:
import torch

a = torch.randn(2,2,4)
print(a)
b = torch.unbind(a, dim=1)
fc = torch.nn.Linear(4,1)
for i in b:
    out = fc(i)
    out = torch.squeeze(out.detach())
    print(out)
print(b)
print(len(b))

tensor([[[-0.6626,  1.8224,  1.3473, -1.2337],
         [ 0.3341, -2.1956, -0.6976,  1.1901]],

        [[-1.7689, -1.5190, -1.6870,  0.2846],
         [-0.6209, -2.1856,  0.5714,  1.2402]]])
tensor([-0.1659, -0.1610])
tensor([-0.0546,  0.4274])
(tensor([[-0.6626,  1.8224,  1.3473, -1.2337],
        [-1.7689, -1.5190, -1.6870,  0.2846]]), tensor([[ 0.3341, -2.1956, -0.6976,  1.1901],
        [-0.6209, -2.1856,  0.5714,  1.2402]]))
2
